"""
TARA Report Generation
Generates markdown and PDF reports from road appraisal results.
"""

import io
from datetime import datetime
from typing import Optional

from output.charts import (
    create_tornado_chart,
    create_waterfall_chart,
    create_traffic_growth_chart,
    create_cashflow_chart,
    create_scenario_chart,
)


def generate_report_markdown(
    road_data: Optional[dict] = None,
    facilities_data: Optional[dict] = None,
    population_data: Optional[dict] = None,
    cba_results: Optional[dict] = None,
    sensitivity_results: Optional[dict] = None,
    equity_results: Optional[dict] = None,
    condition_data: Optional[dict] = None,
    deterioration_summary: Optional[dict] = None,
) -> str:
    """
    Generate a complete markdown appraisal report.

    Args:
        road_data: Output from search_road()
        facilities_data: Output from find_facilities()
        population_data: Output from get_population()
        cba_results: Output from run_cba()
        sensitivity_results: Output from run_sensitivity_analysis()
        equity_results: Output from calculate_equity_score()
        condition_data: Output from analyze_dashcam_media()

    Returns:
        Markdown report string
    """
    sections = []

    road_name = _get_road_name(road_data)
    date_str = datetime.now().strftime("%d %B %Y")

    # Title
    sections.append(f"# TARA Road Appraisal Report")
    sections.append(f"**{road_name}**")
    sections.append(f"")
    sections.append(f"*Generated: {date_str}*")
    sections.append(f"")
    sections.append("---")

    # 1. Executive Summary
    sections.append(_section_executive_summary(road_data, cba_results, sensitivity_results, equity_results))

    # 2. Road Description
    sections.append(_section_road_description(road_data))

    # 3. Corridor Context
    sections.append(_section_corridor_context(population_data, facilities_data))

    # 4. Traffic Analysis
    sections.append(_section_traffic_analysis(cba_results))

    # 5. Economic Analysis
    sections.append(_section_economic_analysis(cba_results))

    # 5b. Deterioration Forecast
    det_data = deterioration_summary or (cba_results.get("deterioration_summary") if cba_results else None)
    det_narr = cba_results.get("deterioration_narrative") if cba_results else None
    if det_data:
        sections.append(_section_deterioration(det_data, det_narr))

    # 6. Sensitivity Analysis
    sections.append(_section_sensitivity_analysis(sensitivity_results))

    # 7. Equity Assessment
    sections.append(_section_equity_assessment(equity_results))

    # 8. Road Condition (if dashcam data available)
    if condition_data and (condition_data.get("found") or condition_data.get("source") == "video_pipeline"):
        sections.append(_section_road_condition(condition_data))

    # 9. Risk Assessment
    sections.append(_section_risk_assessment(cba_results, sensitivity_results))

    # 10. Recommendation
    sections.append(_section_recommendation(cba_results, sensitivity_results, equity_results))

    # Footer
    sections.append("---")
    sections.append("*Report generated by TARA (Transport Appraisal & Risk Analysis)*")
    sections.append("*Built with Claude Opus 4.6 | Anthropic Claude Code Hackathon 2026*")

    return "\n\n".join(sections)


def generate_report_pdf(
    road_data: Optional[dict] = None,
    facilities_data: Optional[dict] = None,
    population_data: Optional[dict] = None,
    cba_results: Optional[dict] = None,
    sensitivity_results: Optional[dict] = None,
    equity_results: Optional[dict] = None,
    condition_data: Optional[dict] = None,
    deterioration_summary: Optional[dict] = None,
) -> bytes:
    """
    Generate a PDF appraisal report.

    Args:
        Same as generate_report_markdown()

    Returns:
        PDF file as bytes
    """
    from fpdf import FPDF

    road_name = _get_road_name(road_data)
    date_str = datetime.now().strftime("%d %B %Y")

    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=20)

    # Title page
    pdf.add_page()
    pdf.set_font("Helvetica", "B", 24)
    pdf.cell(0, 40, "", ln=True)
    pdf.cell(0, 15, "TARA", ln=True, align="C")
    pdf.set_font("Helvetica", "", 14)
    pdf.cell(0, 10, "Transport Appraisal & Risk Analysis", ln=True, align="C")
    pdf.cell(0, 20, "", ln=True)
    pdf.set_font("Helvetica", "B", 18)
    pdf.cell(0, 12, "Road Appraisal Report", ln=True, align="C")
    pdf.cell(0, 10, "", ln=True)
    pdf.set_font("Helvetica", "", 14)
    pdf.cell(0, 10, road_name, ln=True, align="C")
    pdf.cell(0, 10, "", ln=True)
    pdf.set_font("Helvetica", "", 11)
    pdf.cell(0, 8, date_str, ln=True, align="C")
    pdf.cell(0, 15, "", ln=True)
    pdf.set_font("Helvetica", "I", 9)
    pdf.cell(0, 6, "Powered by Claude Opus 4.6", ln=True, align="C")

    # Executive Summary
    pdf.add_page()
    _pdf_section_header(pdf, "1. Executive Summary")
    _pdf_executive_summary(pdf, road_data, cba_results, sensitivity_results, equity_results)

    # Road Description
    _pdf_section_header(pdf, "2. Road Description")
    _pdf_road_description(pdf, road_data)

    # Corridor Context
    _pdf_section_header(pdf, "3. Corridor Context")
    _pdf_corridor_context(pdf, population_data, facilities_data)

    # Traffic Analysis
    pdf.add_page()
    _pdf_section_header(pdf, "4. Traffic Analysis")
    _pdf_traffic_analysis(pdf, cba_results)

    # Economic Analysis
    _pdf_section_header(pdf, "5. Economic Analysis")
    _pdf_economic_analysis(pdf, cba_results)

    # Charts
    _pdf_embed_charts(pdf, cba_results, sensitivity_results)

    # Deterioration Forecast
    det_data = deterioration_summary or (cba_results.get("deterioration_summary") if cba_results else None)
    det_narr = cba_results.get("deterioration_narrative") if cba_results else None
    if det_data:
        pdf.add_page()
        _pdf_section_header(pdf, "5b. Deterioration Forecast")
        _pdf_deterioration(pdf, det_data, det_narr, cba_results)

    # Sensitivity Analysis
    pdf.add_page()
    _pdf_section_header(pdf, "6. Sensitivity Analysis")
    _pdf_sensitivity_analysis(pdf, sensitivity_results)

    # Equity Assessment
    _pdf_section_header(pdf, "7. Equity Assessment")
    _pdf_equity_assessment(pdf, equity_results)

    # Road Condition
    if condition_data and (condition_data.get("found") or condition_data.get("source") == "video_pipeline"):
        pdf.add_page()
        _pdf_section_header(pdf, "8. Road Condition")
        _pdf_road_condition(pdf, condition_data)

    # Risk & Recommendation
    pdf.add_page()
    _pdf_section_header(pdf, "9. Risk Assessment & Recommendation")
    _pdf_risk_recommendation(pdf, cba_results, sensitivity_results, equity_results)

    # Footer
    pdf.cell(0, 15, "", ln=True)
    pdf.set_font("Helvetica", "I", 9)
    pdf.cell(0, 6, "Report generated by TARA (Transport Appraisal & Risk Analysis)", ln=True, align="C")
    pdf.cell(0, 6, "Built with Claude Opus 4.6 | Anthropic Claude Code Hackathon 2026", ln=True, align="C")

    return bytes(pdf.output())


def get_report_summary(
    cba_results: Optional[dict] = None,
    sensitivity_results: Optional[dict] = None,
    equity_results: Optional[dict] = None,
) -> str:
    """Generate a brief summary for the agent to return to the user."""
    parts = ["Report generated successfully."]

    if cba_results:
        s = cba_results.get("summary", {})
        parts.append(
            f"Key results: NPV ${cba_results.get('npv', 0):,.0f}, "
            f"EIRR {s.get('eirr_pct', 'N/A')}%, BCR {cba_results.get('bcr', 0):.2f}."
        )
        if s.get("recommendation"):
            parts.append(f"Recommendation: {s['recommendation']}")

    if equity_results:
        parts.append(f"Equity score: {equity_results.get('overall_score', 'N/A')}/100 ({equity_results.get('classification', '')}).")

    return " ".join(parts)


# --- Markdown Section Helpers ---

def _get_road_name(road_data: Optional[dict]) -> str:
    if road_data:
        name = road_data.get("name") or road_data.get("road_name")
        if name:
            return name
    return "Road Appraisal"


def _section_executive_summary(road_data, cba_results, sensitivity_results, equity_results) -> str:
    lines = ["## 1. Executive Summary", ""]
    road_name = _get_road_name(road_data)
    road_length = road_data.get("total_length_km", "N/A") if road_data else "N/A"

    lines.append(f"This report presents the economic appraisal of the **{road_name}** ({road_length} km).")
    lines.append("")

    if cba_results:
        s = cba_results.get("summary", {})
        lines.append("| Indicator | Value |")
        lines.append("|-----------|-------|")
        lines.append(f"| Net Present Value (NPV) | ${cba_results.get('npv', 0):,.0f} |")
        lines.append(f"| Economic Internal Rate of Return (EIRR) | {s.get('eirr_pct', 'N/A')}% |")
        lines.append(f"| Benefit-Cost Ratio (BCR) | {cba_results.get('bcr', 0):.2f} |")
        lines.append(f"| First Year Rate of Return (FYRR) | {s.get('fyrr_pct', 'N/A')}% |")
        lines.append(f"| NPV per km | ${cba_results.get('npv_per_km', 0):,.0f} |")

        if equity_results:
            lines.append(f"| Equity Score | {equity_results.get('overall_score', 'N/A')}/100 |")

        lines.append("")
        viable = s.get("economically_viable", False)
        lines.append(f"**Verdict: {'ECONOMICALLY VIABLE' if viable else 'NOT ECONOMICALLY VIABLE'}**")
        if s.get("recommendation"):
            lines.append(f"")
            lines.append(f"*{s['recommendation']}*")
    else:
        lines.append("*CBA results not available.*")

    return "\n".join(lines)


def _section_road_description(road_data) -> str:
    lines = ["## 2. Road Description", ""]
    if not road_data or not road_data.get("found"):
        lines.append("*Road data not available.*")
        return "\n".join(lines)

    attrs = road_data.get("attributes", {})
    lines.append(f"| Attribute | Value |")
    lines.append(f"|-----------|-------|")
    lines.append(f"| Name | {road_data.get('name', 'Unknown')} |")
    lines.append(f"| Length | {road_data.get('total_length_km', 'N/A')} km |")
    lines.append(f"| Segments | {road_data.get('segment_count', 'N/A')} |")
    lines.append(f"| Surface | {', '.join(attrs.get('surface_types', ['Unknown']))} |")
    lines.append(f"| Highway Type | {', '.join(attrs.get('highway_types', ['Unknown']))} |")
    if attrs.get("lanes"):
        lines.append(f"| Lanes | {', '.join(str(l) for l in attrs['lanes'])} |")
    if attrs.get("width"):
        lines.append(f"| Width | {attrs['width']} |")

    return "\n".join(lines)


def _section_corridor_context(population_data, facilities_data) -> str:
    lines = ["## 3. Corridor Context", ""]

    if population_data and population_data.get("found"):
        buffers = population_data.get("buffers", {})
        buf_5km = buffers.get("5.0km", buffers.get("5km", {}))
        lines.append("### Population")
        lines.append("")
        lines.append("| Buffer | Population | Density |")
        lines.append("|--------|-----------|---------|")
        for key, buf in buffers.items():
            if buf and buf.get("population"):
                lines.append(f"| {key} | {buf['population']:,} | {buf.get('density_per_km2', 0):,.0f}/km\u00b2 |")
        lines.append("")
        lines.append(f"**Classification:** {population_data.get('classification', 'unknown').title()}")

        pov = population_data.get("poverty_estimate", {})
        if pov.get("population_in_poverty"):
            lines.append(f"")
            lines.append(f"**Poverty estimate:** {pov['population_in_poverty']:,} people below poverty line "
                         f"({pov.get('poverty_ratio', 0):.0%} headcount ratio)")
    else:
        lines.append("*Population data not available.*")

    lines.append("")

    if facilities_data and facilities_data.get("total_count", 0) > 0:
        lines.append("### Nearby Facilities")
        lines.append("")
        lines.append("| Category | Count |")
        lines.append("|----------|-------|")
        for cat, items in facilities_data.get("facilities", {}).items():
            if items:
                lines.append(f"| {cat.title()} | {len(items)} |")
        lines.append(f"")
        lines.append(f"**Total:** {facilities_data['total_count']} facilities within corridor")
    else:
        lines.append("*Facility data not available.*")

    return "\n".join(lines)


def _section_traffic_analysis(cba_results) -> str:
    lines = ["## 4. Traffic Analysis", ""]
    if not cba_results or "traffic_forecast" not in cba_results:
        lines.append("*Traffic data not available.*")
        return "\n".join(lines)

    tf = cba_results["traffic_forecast"]
    summary = tf.get("summary", {})

    lines.append(f"| Parameter | Value |")
    lines.append(f"|-----------|-------|")
    lines.append(f"| Base Year ADT | {tf.get('base_adt', 'N/A'):,.0f} vpd |")
    lines.append(f"| Growth Rate | {tf.get('growth_rate', 0):.1%} |")
    lines.append(f"| Final Year ADT | {summary.get('final_year_adt', 'N/A'):,.0f} vpd |")
    lines.append(f"| Road Capacity | {tf.get('capacity', 'N/A'):,} vpd |")
    lines.append(f"| Capacity Warnings | {summary.get('years_with_capacity_issues', 0)} years |")

    if tf.get("vehicle_split"):
        lines.append("")
        lines.append("**Vehicle Split:**")
        for vc, share in tf["vehicle_split"].items():
            lines.append(f"- {vc}: {share:.0%}")

    return "\n".join(lines)


def _section_economic_analysis(cba_results) -> str:
    lines = ["## 5. Economic Analysis", ""]
    if not cba_results:
        lines.append("*CBA results not available.*")
        return "\n".join(lines)

    s = cba_results.get("summary", {})
    lines.append("### Key Results")
    lines.append("")
    lines.append("| Indicator | Value | Threshold |")
    lines.append("|-----------|-------|-----------|")
    lines.append(f"| NPV | ${cba_results.get('npv', 0):,.0f} | > $0 |")
    lines.append(f"| EIRR | {s.get('eirr_pct', 'N/A')}% | > {cba_results.get('discount_rate', 0.12):.0%} |")
    lines.append(f"| BCR | {cba_results.get('bcr', 0):.2f} | > 1.0 |")
    lines.append(f"| FYRR | {s.get('fyrr_pct', 'N/A')}% | > {cba_results.get('discount_rate', 0.12):.0%} |")
    lines.append("")
    lines.append(f"**PV of Benefits:** ${cba_results.get('pv_benefits', 0):,.0f}")
    lines.append(f"**PV of Costs:** ${cba_results.get('pv_costs', 0):,.0f}")
    lines.append(f"**Economic Construction Cost:** ${cba_results.get('economic_construction_cost', 0):,.0f}")

    return "\n".join(lines)


def _section_deterioration(det_summary: dict, det_narrative: Optional[str] = None) -> str:
    lines = ["## 5b. Deterioration Forecast", ""]

    lines.append("| Parameter | Value |")
    lines.append("|-----------|-------|")
    lines.append(f"| Current IRI | {det_summary.get('iri_current', 'N/A')} m/km |")
    lines.append(f"| Do-Nothing IRI (end) | {det_summary.get('iri_do_nothing_end', 'N/A')} m/km |")
    lines.append(f"| With-Project IRI (end) | {det_summary.get('iri_with_project_end', 'N/A')} m/km |")
    lines.append(f"| IRI Saving | {det_summary.get('iri_saving_end', 'N/A')} m/km |")
    lines.append(f"| Average IRI Benefit | {det_summary.get('avg_iri_saving', 'N/A')} m/km |")
    years_poor = det_summary.get("years_until_poor")
    if years_poor is not None:
        lines.append(f"| Years Until Poor (IRI 10) | {years_poor} |")
    lines.append(f"| Deterioration Rate (k) | {det_summary.get('deterioration_rate_k', 'N/A')} |")
    lines.append(f"| Post-Construction IRI | {det_summary.get('post_construction_iri', 'N/A')} m/km |")

    if det_narrative:
        lines.append("")
        lines.append(det_narrative)

    return "\n".join(lines)


def _section_sensitivity_analysis(sensitivity_results) -> str:
    lines = ["## 6. Sensitivity Analysis", ""]
    if not sensitivity_results:
        lines.append("*Sensitivity analysis not available.*")
        return "\n".join(lines)

    summary = sensitivity_results.get("summary", {})
    lines.append(f"**Most sensitive variable:** {summary.get('most_sensitive_variable', 'N/A')}")

    sv = sensitivity_results.get("switching_values", {})
    if sv:
        lines.append("")
        lines.append("### Switching Values")
        lines.append("*(Change at which NPV becomes zero)*")
        lines.append("")
        lines.append("| Variable | Switching Value |")
        lines.append("|----------|----------------|")
        for var, val in sv.items():
            if var == "traffic_growth":
                lines.append(f"| {var.replace('_', ' ').title()} | {val:+.1%} absolute |")
            else:
                lines.append(f"| {var.replace('_', ' ').title()} | {val:+.0%} |")

    scenarios = sensitivity_results.get("scenarios", {})
    if scenarios:
        lines.append("")
        lines.append("### Scenario Analysis")
        lines.append("")
        lines.append("| Scenario | NPV | BCR | Viable |")
        lines.append("|----------|-----|-----|--------|")
        base = sensitivity_results.get("base_case", {})
        lines.append(f"| Base Case | ${base.get('npv', 0):,.0f} | {base.get('bcr', 0):.2f} | Yes |")
        for name, s in scenarios.items():
            if "error" not in s:
                viable = "Yes" if s.get("viable") else "No"
                lines.append(f"| {name.replace('_', ' ').title()} | ${s.get('npv', 0):,.0f} | {s.get('bcr', 0):.2f} | {viable} |")

    lines.append("")
    lines.append(f"**Risk Assessment:** {summary.get('risk_assessment', 'N/A')}")

    return "\n".join(lines)


def _section_equity_assessment(equity_results) -> str:
    lines = ["## 7. Equity Assessment", ""]
    if not equity_results:
        lines.append("*Equity assessment not available.*")
        return "\n".join(lines)

    lines.append(f"**Overall Score: {equity_results.get('overall_score', 'N/A')}/100** — {equity_results.get('classification', '')}")
    lines.append("")
    lines.append("| Index | Score | Weight |")
    lines.append("|-------|-------|--------|")
    lines.append(f"| Accessibility | {equity_results.get('accessibility_index', 'N/A')}/100 | 30% |")
    lines.append(f"| Population Benefit | {equity_results.get('population_benefit_index', 'N/A')}/100 | 25% |")
    lines.append(f"| Poverty Impact | {equity_results.get('poverty_impact_index', 'N/A')}/100 | 30% |")
    lines.append(f"| Facility Access | {equity_results.get('facility_access_index', 'N/A')}/100 | 15% |")

    breakdown = equity_results.get("breakdown", {})
    if breakdown.get("time_saving_description"):
        lines.append("")
        lines.append(f"*{breakdown['time_saving_description']}*")

    return "\n".join(lines)


def _section_road_condition(condition_data) -> str:
    lines = ["## 8. Road Condition Assessment", ""]
    lines.append(f"**Overall Condition: {condition_data.get('overall_condition', 'N/A')}/100**")
    lines.append("")
    lines.append("| Metric | Value |")
    lines.append("|--------|-------|")

    surface = condition_data.get("surface_type", "N/A")
    if isinstance(surface, str):
        surface = surface.title()
    lines.append(f"| Surface Type | {surface} |")

    # Handle both video pipeline IRI (single float) and old format (dict)
    iri = condition_data.get("iri") or condition_data.get("overall_iri_estimate")
    if isinstance(iri, (int, float)):
        lines.append(f"| IRI Estimate | {iri:.1f} m/km |")
    elif isinstance(iri, dict):
        lines.append(f"| IRI Estimate | {iri.get('min', 'N/A')}-{iri.get('max', 'N/A')} m/km |")

    rating = condition_data.get("condition_rating")
    if rating:
        lines.append(f"| Condition Class | {rating.title()} |")

    drainage = condition_data.get("drainage_condition", "")
    if drainage and drainage != "unknown":
        lines.append(f"| Drainage | {drainage.title()} |")

    defects = condition_data.get("defects", [])
    if defects:
        lines.append("")
        lines.append(f"**Defects:** {', '.join(d.replace('_', ' ').title() for d in defects)}")

    # Per-section condition table (from video pipeline)
    sections_data = condition_data.get("sections", [])
    if sections_data:
        lines.append("")
        lines.append("### Per-Section Condition")
        lines.append("")
        lines.append("| Section | Surface | Condition | IRI | Intervention |")
        lines.append("|---------|---------|-----------|-----|-------------|")
        for sec in sections_data:
            sec_num = sec.get("section_index", 0) + 1
            sec_surf = sec.get("surface_type", "?").title()
            sec_cond = sec.get("condition_class", "?").title()
            sec_iri = sec.get("iri", "?")
            if isinstance(sec_iri, (int, float)):
                sec_iri = f"{sec_iri:.1f}"
            sec_int = sec.get("intervention_name", sec.get("intervention_code", "N/A"))
            lines.append(f"| {sec_num} | {sec_surf} | {sec_cond} | {sec_iri} | {sec_int} |")

    return "\n".join(lines)


def _section_risk_assessment(cba_results, sensitivity_results) -> str:
    lines = ["## 9. Risk Assessment", ""]

    risks = []

    # Technical risks
    if sensitivity_results:
        summary = sensitivity_results.get("summary", {})
        if not summary.get("viable_under_all_scenarios"):
            risks.append("- **Economic risk:** Project becomes non-viable under some scenarios")
        most_sensitive = summary.get("most_sensitive_variable", "")
        if most_sensitive:
            risks.append(f"- **Parameter risk:** Results most sensitive to {most_sensitive.replace('_', ' ')}")

    if cba_results:
        bcr = cba_results.get("bcr", 0)
        if bcr < 1.5:
            risks.append("- **Marginal returns:** BCR below 1.5 suggests limited economic headroom")

        tf = cba_results.get("traffic_forecast", {})
        if tf.get("capacity_warnings"):
            risks.append("- **Capacity risk:** Road may face capacity constraints during analysis period")

    if not risks:
        risks.append("- No significant risks identified")

    risks.insert(0, "### Key Risks")
    lines.extend(risks)

    # Standard implementation risks
    lines.append("")
    lines.append("### Implementation Risks")
    lines.append("- Construction cost overruns (typical range: +10-30%)")
    lines.append("- Construction delays due to weather, procurement, or land acquisition")
    lines.append("- Traffic growth may differ from projections")
    lines.append("- Maintenance funding uncertainty post-construction")

    return "\n".join(lines)


def _section_recommendation(cba_results, sensitivity_results, equity_results) -> str:
    lines = ["## 10. Recommendation", ""]

    if cba_results:
        s = cba_results.get("summary", {})
        viable = s.get("economically_viable", False)

        if viable:
            lines.append("### Proceed with Investment")
            lines.append("")
            lines.append(f"The project is **economically viable** with NPV of ${cba_results.get('npv', 0):,.0f} "
                         f"and EIRR of {s.get('eirr_pct', 'N/A')}%, exceeding the 12% hurdle rate.")
        else:
            lines.append("### Do Not Proceed (Economic Grounds)")
            lines.append("")
            lines.append(f"The project is **not economically viable** with NPV of ${cba_results.get('npv', 0):,.0f}.")

        if equity_results and equity_results.get("overall_score", 0) >= 60:
            lines.append("")
            lines.append(f"The project scores **{equity_results['overall_score']}/100 on equity**, "
                         f"indicating significant positive social impact that may justify investment "
                         f"even with marginal economic returns.")

        lines.append("")
        lines.append("### Caveats")
        lines.append("- Results based on default Uganda parameters; project-specific data improves accuracy")
        lines.append("- Traffic counts should be validated with field surveys")
        lines.append("- Construction cost estimates require detailed engineering design")
        lines.append("")
        lines.append("### Next Steps")
        lines.append("1. Commission detailed traffic count survey")
        lines.append("2. Conduct preliminary engineering design and costing")
        lines.append("3. Perform detailed feasibility study with HDM-4 modelling")
        lines.append("4. Submit to UNRA for project pipeline consideration")
    else:
        lines.append("*Insufficient data for recommendation. Complete the economic analysis first.*")

    return "\n".join(lines)


# --- PDF Section Helpers ---

def _pdf_section_header(pdf, title: str):
    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(0, 12, title, ln=True)
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(0, 3, "", ln=True)


def _pdf_paragraph(pdf, text: str):
    pdf.set_font("Helvetica", "", 10)
    pdf.multi_cell(0, 5, text)
    pdf.cell(0, 3, "", ln=True)


def _pdf_table_row(pdf, cells: list[str], widths: list[int], bold: bool = False):
    pdf.set_font("Helvetica", "B" if bold else "", 9)
    for i, (cell, w) in enumerate(zip(cells, widths)):
        pdf.cell(w, 7, str(cell), border=1, align="C" if i > 0 else "L")
    pdf.ln()


def _pdf_executive_summary(pdf, road_data, cba_results, sensitivity_results, equity_results):
    road_name = _get_road_name(road_data)
    road_length = road_data.get("total_length_km", "N/A") if road_data else "N/A"
    _pdf_paragraph(pdf, f"This report presents the economic appraisal of the {road_name} ({road_length} km).")

    if cba_results:
        s = cba_results.get("summary", {})
        widths = [55, 50]
        _pdf_table_row(pdf, ["Indicator", "Value"], widths, bold=True)
        _pdf_table_row(pdf, ["NPV", f"${cba_results.get('npv', 0):,.0f}"], widths)
        _pdf_table_row(pdf, ["EIRR", f"{s.get('eirr_pct', 'N/A')}%"], widths)
        _pdf_table_row(pdf, ["BCR", f"{cba_results.get('bcr', 0):.2f}"], widths)
        _pdf_table_row(pdf, ["FYRR", f"{s.get('fyrr_pct', 'N/A')}%"], widths)
        if equity_results:
            _pdf_table_row(pdf, ["Equity Score", f"{equity_results.get('overall_score', 'N/A')}/100"], widths)

        pdf.cell(0, 5, "", ln=True)
        viable = s.get("economically_viable", False)
        pdf.set_font("Helvetica", "B", 11)
        pdf.cell(0, 8, f"{'ECONOMICALLY VIABLE' if viable else 'NOT ECONOMICALLY VIABLE'}", ln=True, align="C")
        pdf.set_font("Helvetica", "", 10)
        if s.get("recommendation"):
            _pdf_paragraph(pdf, s["recommendation"])


def _pdf_road_description(pdf, road_data):
    if not road_data or not road_data.get("found"):
        _pdf_paragraph(pdf, "Road data not available.")
        return

    attrs = road_data.get("attributes", {})
    widths = [40, 65]
    _pdf_table_row(pdf, ["Attribute", "Value"], widths, bold=True)
    _pdf_table_row(pdf, ["Name", road_data.get("name", "Unknown")], widths)
    _pdf_table_row(pdf, ["Length", f"{road_data.get('total_length_km', 'N/A')} km"], widths)
    _pdf_table_row(pdf, ["Surface", ", ".join(attrs.get("surface_types", ["Unknown"]))], widths)
    _pdf_table_row(pdf, ["Highway Type", ", ".join(attrs.get("highway_types", ["Unknown"]))], widths)
    pdf.cell(0, 5, "", ln=True)


def _pdf_corridor_context(pdf, population_data, facilities_data):
    if population_data and population_data.get("found"):
        pdf.set_font("Helvetica", "B", 11)
        pdf.cell(0, 8, "Population", ln=True)
        pdf.set_font("Helvetica", "", 10)

        buffers = population_data.get("buffers", {})
        widths = [30, 40, 40]
        _pdf_table_row(pdf, ["Buffer", "Population", "Density"], widths, bold=True)
        for key, buf in buffers.items():
            if buf and buf.get("population"):
                _pdf_table_row(pdf, [key, f"{buf['population']:,}", f"{buf.get('density_per_km2', 0):,.0f}/km2"], widths)

        pdf.cell(0, 3, "", ln=True)
        _pdf_paragraph(pdf, f"Classification: {population_data.get('classification', 'unknown').title()}")
    else:
        _pdf_paragraph(pdf, "Population data not available.")

    if facilities_data and facilities_data.get("total_count", 0) > 0:
        pdf.set_font("Helvetica", "B", 11)
        pdf.cell(0, 8, "Nearby Facilities", ln=True)
        pdf.set_font("Helvetica", "", 10)

        widths = [50, 30]
        _pdf_table_row(pdf, ["Category", "Count"], widths, bold=True)
        for cat, items in facilities_data.get("facilities", {}).items():
            if items:
                _pdf_table_row(pdf, [cat.title(), str(len(items))], widths)
        pdf.cell(0, 3, "", ln=True)


def _pdf_traffic_analysis(pdf, cba_results):
    if not cba_results or "traffic_forecast" not in cba_results:
        _pdf_paragraph(pdf, "Traffic data not available.")
        return

    tf = cba_results["traffic_forecast"]
    summary = tf.get("summary", {})
    widths = [55, 50]
    _pdf_table_row(pdf, ["Parameter", "Value"], widths, bold=True)
    _pdf_table_row(pdf, ["Base Year ADT", f"{tf.get('base_adt', 0):,.0f} vpd"], widths)
    _pdf_table_row(pdf, ["Growth Rate", f"{tf.get('growth_rate', 0):.1%}"], widths)
    _pdf_table_row(pdf, ["Final Year ADT", f"{summary.get('final_year_adt', 0):,.0f} vpd"], widths)
    _pdf_table_row(pdf, ["Road Capacity", f"{tf.get('capacity', 0):,} vpd"], widths)
    pdf.cell(0, 5, "", ln=True)


def _pdf_economic_analysis(pdf, cba_results):
    if not cba_results:
        _pdf_paragraph(pdf, "CBA results not available.")
        return

    s = cba_results.get("summary", {})
    widths = [55, 40, 40]
    _pdf_table_row(pdf, ["Indicator", "Value", "Threshold"], widths, bold=True)
    _pdf_table_row(pdf, ["NPV", f"${cba_results.get('npv', 0):,.0f}", "> $0"], widths)
    _pdf_table_row(pdf, ["EIRR", f"{s.get('eirr_pct', 'N/A')}%", "> 12%"], widths)
    _pdf_table_row(pdf, ["BCR", f"{cba_results.get('bcr', 0):.2f}", "> 1.0"], widths)
    _pdf_table_row(pdf, ["FYRR", f"{s.get('fyrr_pct', 'N/A')}%", "> 12%"], widths)
    pdf.cell(0, 5, "", ln=True)
    _pdf_paragraph(pdf, f"PV Benefits: ${cba_results.get('pv_benefits', 0):,.0f} | PV Costs: ${cba_results.get('pv_costs', 0):,.0f}")


def _pdf_embed_charts(pdf, cba_results, sensitivity_results):
    """Embed chart images into PDF using kaleido."""
    try:
        import tempfile
        import os

        charts = []
        if cba_results:
            charts.append(("Benefit & Cost Breakdown", create_waterfall_chart(cba_results)))
            charts.append(("Annual Cashflows", create_cashflow_chart(cba_results)))
            charts.append(("Traffic Forecast", create_traffic_growth_chart(cba_results)))
        if sensitivity_results:
            charts.append(("Sensitivity Tornado", create_tornado_chart(sensitivity_results)))
            charts.append(("Scenario Comparison", create_scenario_chart(sensitivity_results)))

        for title, fig in charts:
            try:
                with tempfile.NamedTemporaryFile(suffix=".png", delete=False) as tmp:
                    fig.write_image(tmp.name, width=800, height=350, scale=2)
                    pdf.add_page()
                    _pdf_section_header(pdf, title)
                    pdf.image(tmp.name, x=10, w=190)
                    os.unlink(tmp.name)
            except Exception:
                # kaleido not available or chart export failed - skip chart
                continue
    except ImportError:
        pass


def _pdf_deterioration(pdf, det_summary: dict, det_narrative: Optional[str] = None,
                       cba_results: Optional[dict] = None):
    widths = [55, 50]
    _pdf_table_row(pdf, ["Parameter", "Value"], widths, bold=True)
    _pdf_table_row(pdf, ["Current IRI", f"{det_summary.get('iri_current', 'N/A')} m/km"], widths)
    _pdf_table_row(pdf, ["Do-Nothing IRI (end)", f"{det_summary.get('iri_do_nothing_end', 'N/A')} m/km"], widths)
    _pdf_table_row(pdf, ["With-Project IRI (end)", f"{det_summary.get('iri_with_project_end', 'N/A')} m/km"], widths)
    _pdf_table_row(pdf, ["IRI Saving", f"{det_summary.get('iri_saving_end', 'N/A')} m/km"], widths)
    _pdf_table_row(pdf, ["Avg IRI Benefit", f"{det_summary.get('avg_iri_saving', 'N/A')} m/km"], widths)
    years_poor = det_summary.get("years_until_poor")
    if years_poor is not None:
        _pdf_table_row(pdf, ["Years Until Poor", str(years_poor)], widths)
    _pdf_table_row(pdf, ["Post-Construction IRI", f"{det_summary.get('post_construction_iri', 'N/A')} m/km"], widths)
    pdf.cell(0, 5, "", ln=True)

    if det_narrative:
        _pdf_paragraph(pdf, det_narrative)

    # Embed deterioration chart if kaleido available
    try:
        import tempfile
        import os
        from engine.deterioration import create_deterioration_chart, SURFACE_MAP

        iri_current = det_summary.get("iri_current", 11.0)
        surface_type = det_summary.get("surface_type", "paved_fair")
        adt = 1000
        if cba_results and "traffic_forecast" in cba_results:
            adt = cba_results["traffic_forecast"].get("base_adt", 1000)
        fig = create_deterioration_chart(
            iri_current=iri_current,
            surface_type=surface_type,
            adt=adt,
            analysis_period=det_summary.get("analysis_period", 20),
            construction_years=det_summary.get("construction_years", 3),
            road_name=det_summary.get("road_name", "Road"),
        )
        with tempfile.NamedTemporaryFile(suffix=".png", delete=False) as tmp:
            fig.write_image(tmp.name, width=800, height=350, scale=2)
            pdf.image(tmp.name, x=10, w=190)
            os.unlink(tmp.name)
    except Exception:
        pass


def _pdf_sensitivity_analysis(pdf, sensitivity_results):
    if not sensitivity_results:
        _pdf_paragraph(pdf, "Sensitivity analysis not available.")
        return

    summary = sensitivity_results.get("summary", {})
    _pdf_paragraph(pdf, f"Most sensitive variable: {summary.get('most_sensitive_variable', 'N/A')}")

    sv = sensitivity_results.get("switching_values", {})
    if sv:
        pdf.set_font("Helvetica", "B", 11)
        pdf.cell(0, 8, "Switching Values", ln=True)
        widths = [55, 50]
        _pdf_table_row(pdf, ["Variable", "Switching Value"], widths, bold=True)
        for var, val in sv.items():
            _pdf_table_row(pdf, [var.replace("_", " ").title(), f"{val:+.0%}"], widths)

    pdf.cell(0, 5, "", ln=True)
    _pdf_paragraph(pdf, f"Risk: {summary.get('risk_assessment', 'N/A')}")


def _pdf_equity_assessment(pdf, equity_results):
    if not equity_results:
        _pdf_paragraph(pdf, "Equity assessment not available.")
        return

    eq_score = equity_results.get("overall_score", 0)
    if eq_score <= 25:
        eq_label = "Critical - this corridor urgently needs investment for its users"
    elif eq_score <= 50:
        eq_label = "High need - significant infrastructure gaps affect vulnerable users"
    elif eq_score <= 75:
        eq_label = "Moderate - some infrastructure serves users but gaps remain"
    else:
        eq_label = "Well-served - existing infrastructure meets most user needs"

    pdf.set_font("Helvetica", "B", 11)
    pdf.cell(0, 8, f"Overall Score: {eq_score}/100", ln=True)
    pdf.set_font("Helvetica", "I", 10)
    pdf.cell(0, 6, eq_label, ln=True)
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(0, 3, "", ln=True)

    widths = [55, 30, 25]
    _pdf_table_row(pdf, ["Index", "Score", "Weight"], widths, bold=True)
    _pdf_table_row(pdf, ["Accessibility", f"{equity_results.get('accessibility_index', 'N/A')}/100", "30%"], widths)
    _pdf_table_row(pdf, ["Population Benefit", f"{equity_results.get('population_benefit_index', 'N/A')}/100", "25%"], widths)
    _pdf_table_row(pdf, ["Poverty Impact", f"{equity_results.get('poverty_impact_index', 'N/A')}/100", "30%"], widths)
    _pdf_table_row(pdf, ["Facility Access", f"{equity_results.get('facility_access_index', 'N/A')}/100", "15%"], widths)
    pdf.cell(0, 5, "", ln=True)


def _pdf_road_condition(pdf, condition_data):
    widths = [45, 55]
    _pdf_table_row(pdf, ["Metric", "Value"], widths, bold=True)
    _pdf_table_row(pdf, ["Overall Condition", f"{condition_data.get('overall_condition', 'N/A')}/100"], widths)

    surface = condition_data.get("surface_type", "N/A")
    if isinstance(surface, str):
        surface = surface.title()
    _pdf_table_row(pdf, ["Surface Type", surface], widths)

    iri = condition_data.get("iri") or condition_data.get("overall_iri_estimate")
    if isinstance(iri, (int, float)):
        _pdf_table_row(pdf, ["IRI Estimate", f"{iri:.1f} m/km"], widths)
    elif isinstance(iri, dict):
        _pdf_table_row(pdf, ["IRI Estimate", f"{iri.get('min', 'N/A')}-{iri.get('max', 'N/A')} m/km"], widths)

    rating = condition_data.get("condition_rating")
    if rating:
        _pdf_table_row(pdf, ["Condition Class", rating.title()], widths)

    defects = condition_data.get("defects", [])
    if defects:
        pdf.cell(0, 5, "", ln=True)
        _pdf_paragraph(pdf, f"Defects: {', '.join(d.replace('_', ' ').title() for d in defects)}")

    # Per-section table
    sections_data = condition_data.get("sections", [])
    if sections_data:
        pdf.cell(0, 5, "", ln=True)
        pdf.set_font("Helvetica", "B", 11)
        pdf.cell(0, 8, "Per-Section Condition", ln=True)
        sec_widths = [18, 30, 30, 22, 45]
        _pdf_table_row(pdf, ["Sec", "Surface", "Condition", "IRI", "Intervention"], sec_widths, bold=True)
        for sec in sections_data:
            sec_num = str(sec.get("section_index", 0) + 1)
            sec_surf = sec.get("surface_type", "?").title()
            sec_cond = sec.get("condition_class", "?").title()
            sec_iri = sec.get("iri", "?")
            if isinstance(sec_iri, (int, float)):
                sec_iri = f"{sec_iri:.1f}"
            sec_int = sec.get("intervention_name", sec.get("intervention_code", "N/A"))
            if len(str(sec_int)) > 22:
                sec_int = str(sec_int)[:20] + ".."
            _pdf_table_row(pdf, [sec_num, sec_surf, sec_cond, str(sec_iri), str(sec_int)], sec_widths)


def _pdf_risk_recommendation(pdf, cba_results, sensitivity_results, equity_results):
    # Risks
    if sensitivity_results:
        summary = sensitivity_results.get("summary", {})
        _pdf_paragraph(pdf, f"Risk: {summary.get('risk_assessment', 'N/A')}")

    if cba_results:
        s = cba_results.get("summary", {})
        viable = s.get("economically_viable", False)

        pdf.set_font("Helvetica", "B", 12)
        verdict = "PROCEED WITH INVESTMENT" if viable else "DO NOT PROCEED (ECONOMIC GROUNDS)"
        pdf.cell(0, 10, verdict, ln=True, align="C")
        pdf.set_font("Helvetica", "", 10)

        if s.get("recommendation"):
            _pdf_paragraph(pdf, s["recommendation"])

        if equity_results and equity_results.get("overall_score", 0) >= 60:
            _pdf_paragraph(pdf,
                f"Equity score of {equity_results['overall_score']}/100 indicates significant "
                f"positive social impact.")

    _pdf_paragraph(pdf, "Next steps: (1) Commission traffic survey, (2) Detailed engineering design, "
                        "(3) HDM-4 feasibility study, (4) Submit to UNRA pipeline.")
